version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/fitnessmealdb
    depends_on:
      - mongodb
    networks:
      - fitness-network

  mongodb:
    image: mongo:latest
    container_name: fitness-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - fitness-network

networks:
  fitness-network:
    driver: bridge

volumes:
  mongodb_data: